import { Word } from '../types';

export const WORD_IMAGES: Record<string, string> = {
  "one": "1️⃣",
  "two": "2️⃣",
  "three": "3️⃣",
  "four": "4️⃣",
  "five": "5️⃣",
  "six": "6️⃣",
  "seven": "7️⃣",
  "eight": "8️⃣",
  "nine": "9️⃣",
  "ten": "🔟",
  "eleven": "1️⃣1️⃣",
  "twelve": "1️⃣2️⃣",
  "thirteen": "1️⃣3️⃣",
  "fourteen": "1️⃣4️⃣",
  "fifteen": "1️⃣5️⃣",
  "sixteen": "1️⃣6️⃣",
  "seventeen": "1️⃣7️⃣",
  "eighteen": "1️⃣8️⃣",
  "nineteen": "1️⃣9️⃣",
  "twenty": "2️⃣0️⃣",
  "grey": "🩶",
  "red": "🔴",
  "blue": "🔵",
  "green": "🟢",
  "pink": "🩷",
  "white": "⚪",
  "black": "⚫",
  "purple": "🟣",
  "orange": "🟠",
  "yellow": "🟡",
  "brown": "🟤",
  "monday": "1️⃣ 🗓️",
  "tuesday": "2️⃣ 🗓️",
  "wednesday": "3️⃣ 🗓️",
  "thursday": "4️⃣ 🗓️",
  "friday": "5️⃣ 🗓️",
  "saturday": "6️⃣ 🗓️",
  "sunday": "7️⃣ 🗓️",
  "january": "❄️",
  "february": "⛄",
  "march": "🌱",
  "april": "🌧️",
  "may": "🌸",
  "june": "☀️",
  "july": "🏖️",
  "august": "🍉",
  "september": "🎒",
  "october": "🎃",
  "november": "🍂",
  "december": "🎄",
  "spring": "🌱",
  "summer": "☀️",
  "autumn": "🍂",
  "winter": "❄️",
  "window": "🪟",
  "poster": "🪧",
  "bag": "🎒",
  "bin": "🗑️",
  "chair": "🪑",
  "door": "🚪",
  "cupboard": "🗄️",
  "desk": "🪑✏️",
  "book": "📖",
  "board": "👩‍🏫",
  "pencil sharpener": "⚙️✏️",
  "pencil case": "👝✏️",
  "ruler": "📏",
  "rubber": "🧽✏️",
  "pen": "🖊️",
  "pencil": "✏️",
  "box": "📦",
  "glue": "🩹",
  "counters": "🔴🔵",
  "paper": "📄",
  "circle": "🔴",
  "square": "🟩",
  "triangle": "🔺",
  "rectangle": "🟧",
  "oval": "🟣",
  "mum": "👩",
  "dad": "👨",
  "grandma": "👵",
  "grandpa": "👴",
  "brother": "👦",
  "sister": "👧",
  "twin": "👯",
  "uncle": "🧔",
  "auntie": "👱‍♀️",
  "cousin": "🧑‍🤝‍🧑",
  "baby": "👶",
  "toddler": "🧒",
  "child": "🧒",
  "teenager": "🧑‍🎤",
  "adult": "🧑",
  "eldery person": "🧓",
  "elderly person": "🧓",
  "tall": "🦒",
  "short": "🤏",
  "old": "🧓",
  "young": "🧒",
  "pretty": "👸",
  "handsome": "🤴",
  "big": "🐘",
  "small": "🐭",
  "kite": "🪁",
  "scooter": "🛴",
  "teddy": "🧸",
  "doll": "👧🎀",
  "skipping rope": "🏃‍♀️🪢",
  "skateboard": "🛹",
  "ball": "⚽",
  "yoyo": "🪀",
  "robot": "🤖",
  "boat": "⛵",
  "play football": "⚽",
  "play tennis": "🎾",
  "ride a horse": "🏇",
  "run": "🏃",
  "ride a bike": "🚴",
  "rollerblade": "🛼",
  "fish": "🐟",
  "snake": "🐍",
  "tortoise": "🐢",
  "rabbit": "🐰",
  "cat": "🐱",
  "dog": "🐶",
  "spider": "🕷️",
  "mouse": "🐭",
  "hamster": "🐹",
  "bird": "🐦",
  "cow": "🐮",
  "chicken": "🐔",
  "donkey": "🫏",
  "duck": "🦆",
  "goat": "🐐",
  "sheep": "🐑",
  "lion": "🦁",
  "deer": "🦌",
  "breakfast": "🍳",
  "lunch": "🥪",
  "dinner": "🍲",
  "juice": "🧃",
  "cheese": "🧀",
  "meat": "🥩",
  "pasta": "🍝",
  "eggs": "🥚",
  "bread": "🍞",
  "sandwiches": "🥪",
  "milk": "🥛",
  "rice": "🍚",
  "apples": "🍎🍏",
  "carrots": "🥕🥕",
  "tomatoes": "🍅🍅",
  "banana": "🍌🍌",
  "bananas": "🍌🍌",
  "lettuce": "🥬",
  "strawberries": "🍓🍓",
  "head": "🗣️",
  "legs": "🦵",
  "tail": "🐒",
  "wings": "🪽",
  "beak": "🦜",
  "arms": "💪",
  "eyes": "👀",
  "ears": "👂",
  "mouth": "👄",
  "nose": "👃",
  "glasses": "👓",
  "fly": "🦅",
  "swim": "🏊",
  "climb": "🧗",
  "jump": "🦘",
  "talk": "🗣️",
  "walk": "🚶",
  "hat": "🧢",
  "shorts": "🩳",
  "sweater": "🧶👕",
  "shirt": "👔👕",
  "jacket": "🧥💨",
  "skirt": "💃",
  "trousers": "👖",
  "t-shirt": "👕",
  "shoes": "👟",
  "socks": "🧦",
  "blond hair": "👱",
  "curly hair": "👩‍🦱",
  "dark hair": "👦",
  "long hair": "👱‍♀️",
  "straight hair": "👩",
  "picture": "🖼️",
  "wardrobe": "🚪👗",
  "bed": "🛏️",
  "clock": "⏰",
  "bookcase": "🗄️📚",
  "plant": "🪴",
  "television": "📺",
  "table": "🪑🍽️",
  "sofa": "🛋️",
  "cushion": "🛋️🟦",
  "kitchen": "🍳🥘",
  "bathroom": "🛁",
  "bedroom": "🛏️",
  "dining room": "🍽️🪑",
  "garden": "🌳🌷",
  "living room": "🛋️",
  "root": "🥕🌱",
  "flower": "🌸",
  "leaves": "🍃",
  "fruit": "🍎",
  "honey": "🍯",
  "plums": "🟣🟣",
  "insects": "🐞",
  "bricks": "🧱",
  "wood": "🪵",
  "rock": "🪨",
  "mud": "🟤",
  "clay": "🏺",
  "i can": "👍",
  "i can't": "👎",
  "i've got": "🎁",
  "i haven't got": "🚫",
  "i have": "🤲",
  "i have't": "🙅",
  "i haven't": "🙅",
  "i like": "❤️",
  "i don't like": "💔",
  "what's your name?": "🏷️",
  "how are you?": "😊",
  "how old you?": "🎂",
  "how old are you?": "🎂",
  "what colour?": "🎨",
  "what's this?": "❓",
  "i'm": "🙋",
  "he's": "👦",
  "she's": "👧",
  "they're": "🧑‍🤝‍🧑"
};

/**
 * Returns the picture emoji for a word, falling back to topic emoji or a sparkle.
 */
export function getWordImage(word?: Word | null, fallbackEmoji?: string): string {
  if (!word) return fallbackEmoji || '✨';
  if (word.image) return word.image;

  const key = (word.en || '').toLowerCase().trim();
  return WORD_IMAGES[key] || fallbackEmoji || '✨';
}
