/**
 * Complete phonetic transcriptions (IPA) for 1-2 grade English vocabulary.
 */
export const TRANSCRIPTIONS = {
  // Numbers
  "one": "[ wʌn ]",
  "two": "[ tuː ]",
  "three": "[ θriː ]",
  "four": "[ fɔː ]",
  "five": "[ faɪv ]",
  "six": "[ sɪks ]",
  "seven": "[ ˈsevn ]",
  "eight": "[ eɪt ]",
  "nine": "[ naɪn ]",
  "ten": "[ ten ]",
  "eleven": "[ ɪˈlevn ]",
  "twelve": "[ twelv ]",
  "thirteen": "[ ˌθɜːˈtiːn ]",
  "fourteen": "[ ˌfɔːˈtiːn ]",
  "fifteen": "[ ˌfɪfˈtiːn ]",
  "sixteen": "[ ˌsɪksˈtiːn ]",
  "seventeen": "[ ˌsevnˈtiːn ]",
  "eighteen": "[ ˌeɪˈtiːn ]",
  "nineteen": "[ ˌnaɪnˈtiːn ]",
  "twenty": "[ ˈtwenti ]",

  // Colours
  "grey": "[ ɡreɪ ]",
  "red": "[ red ]",
  "blue": "[ bluː ]",
  "green": "[ ɡriːn ]",
  "pink": "[ pɪŋk ]",
  "white": "[ waɪt ]",
  "black": "[ blæk ]",
  "purple": "[ ˈpɜːpl ]",
  "orange": "[ ˈɒrɪndʒ ]",
  "yellow": "[ ˈjeləʊ ]",
  "brown": "[ braʊn ]",

  // Days of the week
  "monday": "[ ˈmʌndeɪ ]",
  "tuesday": "[ ˈtjuːzdeɪ ]",
  "wednesday": "[ ˈwenzdeɪ ]",
  "thursday": "[ ˈθɜːzdeɪ ]",
  "friday": "[ ˈfraɪdeɪ ]",
  "saturday": "[ ˈsætədeɪ ]",
  "sunday": "[ ˈsʌndeɪ ]",

  // Months
  "january": "[ ˈdʒænjuəri ]",
  "february": "[ ˈfebruəri ]",
  "march": "[ mɑːtʃ ]",
  "april": "[ ˈeɪprəl ]",
  "may": "[ meɪ ]",
  "june": "[ dʒuːn ]",
  "july": "[ dʒuˈlaɪ ]",
  "august": "[ ˈɔːɡəst ]",
  "september": "[ sepˈtembə ]",
  "october": "[ ɒkˈtəʊbə ]",
  "november": "[ nəʊˈvembə ]",
  "december": "[ dɪˈsembə ]",

  // Seasons
  "spring": "[ sprɪŋ ]",
  "summer": "[ ˈsʌmə ]",
  "autumn": "[ ˈɔːtəm ]",
  "winter": "[ ˈwɪntə ]",

  // Classroom objects
  "window": "[ ˈwɪndəʊ ]",
  "poster": "[ ˈpəʊstə ]",
  "bag": "[ bæɡ ]",
  "bin": "[ bɪn ]",
  "chair": "[ tʃeə ]",
  "door": "[ dɔː ]",
  "cupboard": "[ ˈkʌbəd ]",
  "desk": "[ desk ]",
  "book": "[ bʊk ]",
  "board": "[ bɔːd ]",
  "pencil sharpener": "[ ˈpensl ˈʃɑːpnə ]",
  "pencil case": "[ ˈpensl keɪs ]",
  "ruler": "[ ˈruːlə ]",
  "rubber": "[ ˈrʌbə ]",
  "pen": "[ pen ]",
  "pencil": "[ ˈpensl ]",
  "box": "[ bɒks ]",
  "glue": "[ ɡluː ]",
  "counters": "[ ˈkaʊntəz ]",
  "paper": "[ ˈpeɪpə ]",
  "circle": "[ ˈsɜːkl ]",
  "square": "[ skweə ]",
  "triangle": "[ ˈtraɪæŋɡl ]",
  "rectangle": "[ ˈrektæŋɡl ]",
  "oval": "[ ˈəʊvl ]",

  // Family
  "mum": "[ mʌm ]",
  "dad": "[ dæd ]",
  "grandma": "[ ˈɡrænmɑː ]",
  "grandpa": "[ ˈɡrænpɑː ]",
  "brother": "[ ˈbrʌðə ]",
  "sister": "[ ˈsɪstə ]",
  "twin": "[ twɪn ]",
  "uncle": "[ ˈʌŋkl ]",
  "auntie": "[ ˈɑːnti ]",
  "cousin": "[ ˈkʌzn ]",
  "baby": "[ ˈbeɪbi ]",
  "toddler": "[ ˈtɒdlə ]",
  "child": "[ tʃaɪld ]",
  "teenager": "[ ˈtiːneɪdʒə ]",
  "adult": "[ ˈædʌlt ]",
  "elderly person": "[ ˈeldəli ˈpɜːsn ]",
  "eldery person": "[ ˈeldəli ˈpɜːsn ]",
  "he": "[ hiː ]",
  "she": "[ ʃiː ]",

  // Adjectives
  "tall": "[ tɔːl ]",
  "short": "[ ʃɔːt ]",
  "old": "[ əʊld ]",
  "young": "[ jʌŋ ]",
  "pretty": "[ ˈprɪti ]",
  "handsome": "[ ˈhænsəm ]",
  "big": "[ bɪɡ ]",
  "small": "[ smɔːl ]",

  // Toys
  "kite": "[ kaɪt ]",
  "scooter": "[ ˈskuːtə ]",
  "teddy": "[ ˈtedi ]",
  "doll": "[ dɒl ]",
  "skipping rope": "[ ˈskɪpɪŋ rəʊp ]",
  "skateboard": "[ ˈskeɪtbɔːd ]",
  "ball": "[ bɔːl ]",
  "yoyo": "[ ˈjəʊjəʊ ]",
  "robot": "[ ˈrəʊbɒt ]",
  "boat": "[ bəʊt ]",

  // Activities
  "play football": "[ pleɪ ˈfʊtbɔːl ]",
  "play tennis": "[ pleɪ ˈtenɪs ]",
  "ride a horse": "[ raɪd ə hɔːs ]",
  "run": "[ rʌn ]",
  "ride a bike": "[ raɪd ə baɪk ]",
  "rollerblade": "[ ˈrəʊləbleɪd ]",

  // Pets
  "fish": "[ fɪʃ ]",
  "snake": "[ sneɪk ]",
  "tortoise": "[ ˈtɔːtəs ]",
  "rabbit": "[ ˈræbɪt ]",
  "cat": "[ kæt ]",
  "dog": "[ dɒɡ ]",
  "spider": "[ ˈspaɪdə ]",
  "mouse": "[ maʊs ]",
  "hamster": "[ ˈhæmstə ]",
  "bird": "[ bɜːd ]",

  // Farm animals
  "cow": "[ kaʊ ]",
  "chicken": "[ ˈtʃɪkɪn ]",
  "donkey": "[ ˈdɒŋki ]",
  "duck": "[ dʌk ]",
  "goat": "[ ɡəʊt ]",
  "sheep": "[ ʃiːp ]",

  // Wild animals
  "lion": "[ ˈlaɪən ]",
  "deer": "[ dɪə ]",

  // Food and drink (including Bright Ideas 1 p.52)
  "breakfast": "[ ˈbrekfəst ]",
  "lunch": "[ lʌntʃ ]",
  "dinner": "[ ˈdɪnə ]",
  "juice": "[ dʒuːs ]",
  "cheese": "[ tʃiːz ]",
  "meat": "[ miːt ]",
  "pasta": "[ ˈpæstə ]",
  "eggs": "[ eɡz ]",
  "bread": "[ bred ]",
  "sandwiches": "[ ˈsænwɪdʒɪz ]",
  "milk": "[ mɪlk ]",
  "rice": "[ raɪs ]",

  // Fruit and vegetables
  "apples": "[ ˈæplz ]",
  "carrots": "[ ˈkærəts ]",
  "tomatoes": "[ təˈmɑːtəʊz ]",
  "banana": "[ bəˈnɑːnə ]",
  "bananas": "[ bəˈnɑːnəz ]",
  "lettuce": "[ ˈletɪs ]",
  "strawberries": "[ ˈstrɔːbəriz ]",

  // Body
  "head": "[ hed ]",
  "legs": "[ leɡz ]",
  "tail": "[ teɪl ]",
  "wings": "[ wɪŋz ]",
  "beak": "[ biːk ]",
  "arms": "[ ɑːmz ]",

  // Face
  "eyes": "[ aɪz ]",
  "ears": "[ ɪəz ]",
  "mouth": "[ maʊθ ]",
  "nose": "[ nəʊz ]",
  "glasses": "[ ˈɡlɑːsɪz ]",

  // Abilities
  "fly": "[ flaɪ ]",
  "swim": "[ swɪm ]",
  "climb": "[ klaɪm ]",
  "jump": "[ dʒʌmp ]",
  "talk": "[ tɔːk ]",
  "walk": "[ wɔːk ]",

  // Clothes
  "hat": "[ hæt ]",
  "shorts": "[ ʃɔːts ]",
  "sweater": "[ ˈswetə ]",
  "shirt": "[ ʃɜːt ]",
  "jacket": "[ ˈdʒækɪt ]",
  "skirt": "[ skɜːt ]",
  "trousers": "[ ˈtraʊzəz ]",
  "t-shirt": "[ ˈtiː ʃɜːt ]",
  "shoes": "[ ʃuːz ]",
  "socks": "[ sɒks ]",

  // Hair
  "blond hair": "[ blɒnd heə ]",
  "curly hair": "[ ˈkɜːli heə ]",
  "dark hair": "[ dɑːk heə ]",
  "long hair": "[ lɒŋ heə ]",
  "straight hair": "[ streɪt heə ]",

  // At home
  "picture": "[ ˈpɪktʃə ]",
  "wardrobe": "[ ˈwɔːdrəʊb ]",
  "bed": "[ bed ]",
  "clock": "[ klɒk ]",
  "bookcase": "[ ˈbʊkkeɪs ]",
  "plant": "[ plɑːnt ]",
  "television": "[ ˈtelɪvɪʒn ]",
  "table": "[ ˈteɪbl ]",
  "sofa": "[ ˈsəʊfə ]",
  "cushion": "[ ˈkʊʃn ]",

  // Rooms
  "kitchen": "[ ˈkɪtʃɪn ]",
  "bathroom": "[ ˈbɑːθruːm ]",
  "bedroom": "[ ˈbedruːm ]",
  "dining room": "[ ˈdaɪnɪŋ ruːm ]",
  "garden": "[ ˈɡɑːdn ]",
  "living room": "[ ˈlɪvɪŋ ruːm ]",

  // Garden
  "root": "[ ruːt ]",
  "flower": "[ ˈflaʊə ]",
  "leaves": "[ liːvz ]",
  "fruit": "[ fruːt ]",
  "honey": "[ ˈhʌni ]",
  "plums": "[ plʌmz ]",
  "insects": "[ ˈɪnsekts ]",

  // Building materials
  "bricks": "[ brɪks ]",
  "wood": "[ wʊd ]",
  "rock": "[ rɒk ]",
  "mud": "[ mʌd ]",
  "clay": "[ kleɪ ]",

  // Actions
  "i can": "[ aɪ kæn ]",
  "i can't": "[ aɪ kɑːnt ]",
  "i've got": "[ aɪv ɡɒt ]",
  "i haven't got": "[ aɪ ˈhævnt ɡɒt ]",
  "i have": "[ aɪ hæv ]",
  "i haven't": "[ aɪ ˈhævnt ]",
  "i have't": "[ aɪ ˈhævnt ]",
  "i like": "[ aɪ laɪk ]",
  "i don't like": "[ aɪ dəʊnt laɪk ]",

  // Introductions
  "what's your name?": "[ wɒts jɔː neɪm ]",
  "how are you?": "[ haʊ ɑː juː ]",
  "how old you?": "[ haʊ əʊld juː ]",
  "how old are you?": "[ haʊ əʊld ɑː juː ]",
  "what colour?": "[ wɒt ˈkʌlə ]",
  "what's this?": "[ wɒts ðɪs ]",

  // Pronouns
  "i'm": "[ aɪm ]",
  "he's": "[ hiːz ]",
  "she's": "[ ʃiːz ]",
  "they're": "[ ðeə ]",

  // Instructions
  "listen": "[ ˈlɪsn ]",
  "point": "[ pɔɪnt ]",
  "repeat": "[ rɪˈpiːt ]",
  "say": "[ seɪ ]",
  "look": "[ lʊk ]",
  "answer": "[ ˈɑːnsə ]",
  "watch": "[ wɒtʃ ]",
  "complete": "[ kəmˈpliːt ]",
  "sing": "[ sɪŋ ]",
  "match": "[ mætʃ ]",
  "ask": "[ ɑːsk ]",
  "guess": "[ ɡes ]",
  "join": "[ dʒɔɪn ]",
  "put": "[ pʊt ]",
  "find": "[ faɪnd ]",
  "tick": "[ tɪk ]",
  "cross": "[ krɒs ]",
  "colour": "[ ˈkʌlə ]",
  "play": "[ pleɪ ]",
  "write": "[ raɪt ]",
  "read": "[ riːd ]",
  "make": "[ meɪk ]",

  // New Grade 1 words
  "park": "[ pɑːk ]",
  "playground": "[ ˈpleɪɡraʊnd ]",
  "farm": "[ fɑːm ]",
  "teacher": "[ ˈtiːtʃə ]",
  "stickers": "[ ˈstɪkəz ]",
  "sheet": "[ ʃiːt ]",
  "text": "[ tekst ]",
  "photo": "[ ˈfəʊtəʊ ]",
  "message": "[ ˈmesɪdʒ ]",
  "hello": "[ həˈləʊ ]",
  "bye": "[ baɪ ]",
  "draw": "[ drɔː ]",
  "check": "[ tʃek ]",
  "turn": "[ tɜːn ]",
  "remember": "[ rɪˈmembə ]",
  "practise": "[ ˈpræktɪs ]",
  "again": "[ əˈɡen ]",
  "tired": "[ ˈtaɪəd ]",
  "different": "[ ˈdɪfrənt ]",
  "activity": "[ ækˈtɪvəti ]",
  "tree": "[ triː ]",

  // Questions
  "what": "[ wɒt ]",
  "where": "[ weə ]",
  "who": "[ huː ]",
  "how": "[ haʊ ]",
  "which": "[ wɪtʃ ]",

  // Helper words
  "lots": "[ lɒts ]",
  "only": "[ ˈəʊnli ]",
  "other": "[ ˈʌðə ]",
  "maybe": "[ ˈmeɪbi ]",
  "then": "[ ðen ]",
  "about": "[ əˈbaʊt ]",

  // Pronouns
  "we": "[ wiː ]",
  "they": "[ ðeɪ ]",
  "my": "[ maɪ ]",
  "me": "[ miː ]",
  "this": "[ ðɪs ]",
  "it's": "[ ɪts ]",
  "that's": "[ ðæts ]",
  "here": "[ hɪə ]",

  // Introductions & Courtesy
  "please": "[ pliːz ]",
  "thanks": "[ θæŋks ]",
  "fine": "[ faɪn ]",

  // Instructions
  "think": "[ θɪŋk ]",
  "pair": "[ peə ]",
  "share": "[ ʃeə ]",
  "create": "[ kriˈeɪt ]",
  "miss": "[ mɪs ]",

  // Colours & Family
  "rainbow": "[ ˈreɪnbəʊ ]",
  "people": "[ ˈpiːpl ]",

  // Birthday
  "board game": "[ ˈbɔːd ɡeɪm ]",
  "jigsaw": "[ ˈdʒɪɡsɔː ]",
  "balloon": "[ bəˈluːn ]",
  "ballon": "[ bəˈluːn ]",
  "camera": "[ ˈkæmərə ]",
  "dress": "[ dres ]",
  "necklace": "[ ˈnekləs ]",
  "chocolate": "[ ˈtʃɒklət ]",
  "umbrella": "[ ʌmˈbrelə ]",
  "dinosaur": "[ ˈdaɪnəsɔː ]",

  // Feelings
  "happy": "[ ˈhæpi ]",
  "sad": "[ sæd ]",
  "hungry": "[ ˈhʌŋɡri ]",
  "thirsty": "[ ˈθɜːsti ]",
  "angry": "[ ˈæŋɡri ]",

  // Jobs
  "police officer": "[ pəˈliːs ˈɒfɪsə ]",
  "cook": "[ kʊk ]",
  "football player": "[ ˈfʊtbɔːl ˈpleɪə ]",
  "scientist": "[ ˈsaɪəntɪst ]",
  "zoo keeper": "[ ˈzuː ˈkiːpə ]",
  "doctor": "[ ˈdɒktə ]",
  "builder": "[ ˈbɪldə ]",
  "waiter": "[ ˈweɪtə ]",
  "farmer": "[ ˈfɑːmə ]",
  "teacher": "[ ˈtiːtʃə ]",

  // Transport
  "bus": "[ bʌs ]",
  "car": "[ kɑː ]",
  "motorbike": "[ ˈməʊtəbaɪk ]",
  "lorry": "[ ˈlɒri ]",
  "plane": "[ pleɪn ]",
  "train": "[ treɪn ]",

  // Senses
  "see": "[ siː ]",
  "smell": "[ smel ]",
  "taste": "[ teɪst ]",
  "touch": "[ tʌtʃ ]",
  "hear": "[ hɪə ]",

  // Town
  "castle": "[ ˈkɑːsl ]",
  "cinema": "[ ˈsɪnəmə ]",
  "museum": "[ mjuˈziːəm ]",
  "station": "[ ˈsteɪʃn ]",
  "hospital": "[ ˈhɒspɪtl ]",
  "park": "[ pɑːk ]",
  "library": "[ ˈlaɪbrəri ]",
  "shop": "[ ʃɒp ]",
  "restaurant": "[ ˈrestrɒnt ]",
  "swimming pool": "[ ˈswɪmɪŋ puːl ]",
  "pet shop": "[ ˈpet ʃɒp ]",
  "toy shop": "[ ˈtɔɪ ʃɒp ]",
  "school": "[ skuːl ]",
  "bookshop": "[ ˈbʊkʃɒp ]",

  // Prepositions of place
  "next to": "[ nekst tuː ]",
  "between": "[ bɪˈtwiːn ]",
  "in front of": "[ ɪn frʌnt ɒv ]",
  "behind": "[ bɪˈhaɪnd ]",
  "opposite": "[ ˈɒpəzɪt ]",
  "above": "[ əˈbʌv ]",

  // Directions
  "turn left": "[ tɜːn left ]",
  "turn right": "[ tɜːn raɪt ]",
  "go straight on": "[ ɡəʊ streɪt ɒn ]",

  // Food & drink + and Fruit & vegetables +
  "chips": "[ tʃɪps ]",
  "sausages": "[ ˈsɒsɪdʒɪz ]",
  "ice cream": "[ ˌaɪs ˈkriːm ]",
  "water": "[ ˈwɔːtər ]",
  "watermelon": "[ ˈwɔːtərmelən ]",
  "grapes": "[ ɡreɪps ]",
  "pineapple": "[ ˈpaɪnæpl ]",
  "spinach": "[ ˈspɪnɪtʃ ]",
  "potatoes": "[ pəˈteɪtəʊz ]",

  // 1st Grade Additional Topics additions
  "after": "[ ˈɑːftə ]",
  "and": "[ ænd ]",
  "animal": "[ ˈænɪml ]",
  "another": "[ əˈnʌðə ]",
  "art": "[ ɑːt ]",
  "below": "[ bɪˈləʊ ]",
  "both": "[ bəʊθ ]",
  "boy": "[ bɔɪ ]",
  "card": "[ kɑːd ]",
  "chant": "[ tʃɑːnt ]",
  "children": "[ ˈtʃɪldrən ]",
  "class": "[ klɑːs ]",
  "classroom": "[ ˈklɑːsruːm ]",
  "count": "[ kaʊnt ]",
  "country": "[ ˈkʌntri ]",
  "craft": "[ krɑːft ]",
  "cup": "[ kʌp ]",
  "day": "[ deɪ ]",
  "dear": "[ dɪə ]",
  "design": "[ dɪˈzaɪn ]",
  "else": "[ els ]",
  "family": "[ ˈfæməli ]",
  "favourite": "[ ˈfeɪvərɪt ]",
  "follow": "[ ˈfɒləʊ ]",
  "food": "[ fuːd ]",
  "friend": "[ frend ]",
  "from": "[ frɒm ]",
  "fun": "[ fʌn ]",
  "game": "[ ɡeɪm ]",
  "girl": "[ ɡɜːl ]",
  "go back": "[ ɡəʊ bæk ]",
  "group": "[ ɡruːp ]",
  "have you got": "[ hæv juː ɡɒt ]",
  "hey": "[ heɪ ]",
  "hi": "[ haɪ ]",
  "i don't know": "[ aɪ dəʊnt nəʊ ]",
  "in": "[ ɪn ]",
  "lesson": "[ ˈlesn ]",
  "love": "[ lʌv ]",
  "middle": "[ ˈmɪdl ]",
  "moon": "[ muːn ]",
  "music": "[ ˈmjuːzɪk ]",
  "need": "[ niːd ]",
  "no": "[ nəʊ ]",
  "number": "[ ˈnʌmbə ]",
  "order": "[ ˈɔːdə ]",
  "our": "[ ˈaʊə ]",
  "party": "[ ˈpɑːti ]",
  "question": "[ ˈkwestʃən ]",
  "right": "[ raɪt ]",
  "ruby": "[ ˈruːbi ]",
  "scissors": "[ ˈsɪzəz ]",
  "shapes": "[ ʃeɪps ]",
  "story": "[ ˈstɔːri ]",
  "sun": "[ sʌn ]",
  "task": "[ tɑːsk ]",
  "tell": "[ tel ]",
  "things": "[ θɪŋz ]",
  "this is": "[ ðɪs ɪz ]",
  "through": "[ θruː ]",
  "today": "[ təˈdeɪ ]",
  "tomorrow": "[ təˈmɒrəʊ ]",
  "too": "[ tuː ]",
  "toys": "[ tɔɪz ]",
  "trace": "[ treɪs ]",
  "true": "[ truː ]",
  "wait": "[ weɪt ]",
  "wheel": "[ wiːl ]",
  "who's this": "[ huːz ðɪs ]",
  "with": "[ wɪð ]",
  "yes": "[ jes ]",
  "yesterday": "[ ˈjestədeɪ ]",
  "your": "[ jɔː ]"
};

