export const WORD_IMAGES = {
  "one": "1️⃣",
  "two": "2️⃣",
  "three": "3️⃣",
  "four": "4️⃣",
  "five": "5️⃣",
  "six": "6️⃣",
  "seven": "7️⃣",
  "eight": "8️⃣",
  "nine": "9️⃣",
  "ten": "🔟",
  "eleven": "1️⃣1️⃣",
  "twelve": "1️⃣2️⃣",
  "thirteen": "1️⃣3️⃣",
  "fourteen": "1️⃣4️⃣",
  "fifteen": "1️⃣5️⃣",
  "sixteen": "1️⃣6️⃣",
  "seventeen": "1️⃣7️⃣",
  "eighteen": "1️⃣8️⃣",
  "nineteen": "1️⃣9️⃣",
  "twenty": "2️⃣0️⃣",
  "grey": "🩶",
  "red": "🔴",
  "blue": "🔵",
  "green": "🟢",
  "pink": "🩷",
  "white": "⚪",
  "black": "⚫",
  "purple": "🟣",
  "orange": "🟠",
  "yellow": "🟡",
  "brown": "🟤",
  "monday": "1️⃣ 🗓️",
  "tuesday": "2️⃣ 🗓️",
  "wednesday": "3️⃣ 🗓️",
  "thursday": "4️⃣ 🗓️",
  "friday": "5️⃣ 🗓️",
  "saturday": "6️⃣ 🗓️",
  "sunday": "7️⃣ 🗓️",
  "january": "❄️",
  "february": "⛄",
  "march": "🌱",
  "april": "🌧️",
  "may": "🌸",
  "june": "☀️",
  "july": "🏖️",
  "august": "🍉",
  "september": "🎒",
  "october": "🎃",
  "november": "🍂",
  "december": "🎄",
  "spring": "🌱",
  "summer": "☀️",
  "autumn": "🍂",
  "winter": "❄️",
  "window": "🪟",
  "poster": "🪧",
  "bag": "🎒",
  "bin": "🗑️",
  "chair": "🪑",
  "door": "🚪",
  "cupboard": "🗄️",
  "desk": "🪑✏️",
  "book": "📖",
  "board": "👩‍🏫",
  "pencil sharpener": "⚙️✏️",
  "pencil case": "👝✏️",
  "ruler": "📏",
  "rubber": "🧽✏️",
  "pen": "🖊️",
  "pencil": "✏️",
  "box": "📦",
  "glue": "🩹",
  "counters": "🔴🔵",
  "paper": "📄",
  "circle": "🔴",
  "square": "🟩",
  "triangle": "🔺",
  "rectangle": "🟧",
  "oval": "🟣",
  "mum": "👩",
  "dad": "👨",
  "grandma": "👵",
  "grandpa": "👴",
  "brother": "👦",
  "sister": "👧",
  "twin": "👯",
  "uncle": "🧔",
  "auntie": "👱‍♀️",
  "cousin": "🧑‍🤝‍🧑",
  "baby": "👶",
  "toddler": "🧒",
  "child": "🧒",
  "teenager": "🧑‍🎤",
  "adult": "🧑",
  "eldery person": "🧓",
  "elderly person": "🧓",
  "tall": "🦒",
  "short": "🤏",
  "old": "🧓",
  "young": "🧒",
  "pretty": "👸",
  "handsome": "🤴",
  "big": "🐘",
  "small": "🐭",
  "kite": "🪁",
  "scooter": "🛴",
  "teddy": "🧸",
  "doll": "👧🎀",
  "skipping rope": "🏃‍♀️🪢",
  "skateboard": "🛹",
  "ball": "⚽",
  "yoyo": "🪀",
  "robot": "🤖",
  "boat": "⛵",
  "play football": "⚽",
  "play tennis": "🎾",
  "ride a horse": "🏇",
  "run": "🏃",
  "ride a bike": "🚴",
  "rollerblade": "🛼",
  "fish": "🐟",
  "snake": "🐍",
  "tortoise": "🐢",
  "rabbit": "🐰",
  "cat": "🐱",
  "dog": "🐶",
  "spider": "🕷️",
  "mouse": "🐭",
  "hamster": "🐹",
  "bird": "🐦",
  "cow": "🐮",
  "chicken": "🐔",
  "donkey": "🫏",
  "duck": "🦆",
  "goat": "🐐",
  "sheep": "🐑",
  "lion": "🦁",
  "deer": "🦌",
  "breakfast": "🍳",
  "lunch": "🥪",
  "dinner": "🍲",
  "juice": "🧃",
  "cheese": "🧀",
  "meat": "🥩",
  "pasta": "🍝",
  "eggs": "🥚",
  "bread": "🍞",
  "sandwiches": "🥪",
  "milk": "🥛",
  "rice": "🍚",
  "apples": "🍎🍏",
  "carrots": "🥕🥕",
  "tomatoes": "🍅🍅",
  "banana": "🍌🍌",
  "bananas": "🍌🍌",
  "lettuce": "🥬",
  "strawberries": "🍓🍓",
  "head": "🗣️",
  "legs": "🦵",
  "tail": "🐒",
  "wings": "🪽",
  "beak": "🦜",
  "arms": "💪",
  "eyes": "👀",
  "ears": "👂",
  "mouth": "👄",
  "nose": "👃",
  "glasses": "👓",
  "fly": "🦅",
  "swim": "🏊",
  "climb": "🧗",
  "jump": "🦘",
  "talk": "🗣️",
  "walk": "🚶",
  "hat": "🧢",
  "shorts": "🩳",
  "sweater": "🧶👕",
  "shirt": "👔👕",
  "jacket": "🧥💨",
  "skirt": "💃",
  "trousers": "👖",
  "t-shirt": "👕",
  "shoes": "👟",
  "socks": "🧦",
  "blond hair": "👱",
  "curly hair": "👩‍🦱",
  "dark hair": "👦",
  "long hair": "👱‍♀️",
  "straight hair": "👩",
  "picture": "🖼️",
  "wardrobe": "🚪👗",
  "bed": "🛏️",
  "clock": "⏰",
  "bookcase": "🗄️📚",
  "plant": "🪴",
  "television": "📺",
  "table": "🪑🍽️",
  "sofa": "🛋️",
  "cushion": "🛋️🟦",
  "kitchen": "🍳🥘",
  "bathroom": "🛁",
  "bedroom": "🛏️",
  "dining room": "🍽️🪑",
  "garden": "🌳🌷",
  "living room": "🛋️",
  "root": "🥕🌱",
  "flower": "🌸",
  "leaves": "🍃",
  "fruit": "🍎",
  "honey": "🍯",
  "plums": "🟣🟣",
  "insects": "🐞",
  "bricks": "🧱",
  "wood": "🪵",
  "rock": "🪨",
  "mud": "🟤",
  "clay": "🏺",
  "i can": "👍",
  "i can't": "👎",
  "i've got": "🎁",
  "i haven't got": "🚫",
  "i have": "🤲",
  "i have't": "🙅",
  "i haven't": "🙅",
  "i like": "❤️",
  "i don't like": "💔",
  "what's your name?": "🏷️",
  "how are you?": "😊",
  "how old you?": "🎂",
  "how old are you?": "🎂",
  "what colour?": "🎨",
  "what's this?": "❓",
  "i'm": "🙋",
  "he's": "👦",
  "she's": "👧",
  "they're": "🧑‍🤝‍🧑",
  "listen": "👂",
  "point": "👉",
  "repeat": "🔁",
  "say": "💬",
  "look": "👀",
  "answer": "🙋",
  "watch": "📺",
  "complete": "🧩",
  "sing": "🎤",
  "match": "🎯",
  "ask": "❓",
  "guess": "💡",
  "join": "🔗",
  "put": "📥",
  "find": "🔍",
  "tick": "✅",
  "cross": "❌",
  "colour": "🖍️",
  "play": "🎲",
  "write": "✍️",
  "read": "📖",
  "make": "✂️",
  "park": "🏞️",
  "playground": "🛝",
  "farm": "🚜",
  "teacher": "👩‍🏫",
  "stickers": "⭐",
  "sheet": "📝",
  "text": "📄",
  "photo": "📸",
  "message": "💬",
  "hello": "👋",
  "bye": "👋",
  "draw": "🎨",
  "check": "✔️",
  "turn": "🔄",
  "remember": "🧠",
  "practise": "🎯",
  "again": "🔁",
  "tired": "🥱",
  "different": "🔀",
  "activity": "🏃",
  "tree": "🌳",
  "what": "❓",
  "where": "📍",
  "who": "👤",
  "how": "⚙️",
  "which": "👉",
  "lots": "📦",
  "only": "1️⃣",
  "other": "👥",
  "maybe": "🤔",
  "then": "➡️",
  "about": "📖",
  "we": "🧑‍🤝‍🧑",
  "they": "👥",
  "my": "🙋‍♂️",
  "me": "🙋",
  "this": "👉",
  "it's": "📍",
  "that's": "👉",
  "here": "📌",
  "please": "🙏",
  "thanks": "👍",
  "fine": "😊",
  "think": "💭",
  "pair": "👥",
  "share": "🤝",
  "create": "🎨",
  "miss": "⏭️",
  "rainbow": "🌈",
  "people": "🧑‍🤝‍🧑",
  "board game": "🎲",
  "jigsaw": "🧩",
  "balloon": "🎈",
  "ballon": "🎈",
  "camera": "📷",
  "dress": "👗",
  "necklace": "📿",
  "chocolate": "🍫",
  "birthday:watch": "⌚",
  "umbrella": "☂️",
  "dinosaur": "🦖",
  "happy": "😊",
  "sad": "😢",
  "hungry": "😋",
  "thirsty": "🥤",
  "angry": "😠",

  // Jobs
  "police officer": "👮",
  "cook": "👨‍🍳",
  "football player": "⚽",
  "scientist": "🔬",
  "zoo keeper": "🦁",
  "doctor": "🩺",
  "builder": "👷",
  "waiter": "🤵",
  "farmer": "🧑‍🌾",

  // Transport
  "bus": "🚌",
  "car": "🚗",
  "motorbike": "🏍️",
  "lorry": "🚛",
  "plane": "✈️",
  "train": "🚆",

  // Senses
  "see": "👀",
  "smell": "👃",
  "taste": "👅",
  "touch": "✋",
  "hear": "👂",

  // Town
  "castle": "🏰",
  "cinema": "🎬",
  "museum": "🏛️",
  "station": "🚉",
  "hospital": "🏥",
  "library": "📚",
  "shop": "🏪",
  "restaurant": "🍽️",
  "swimming pool": "🏊",
  "pet shop": "🐾",
  "toy shop": "🧸",
  "school": "🏫",
  "bookshop": "📖",

  // Prepositions of place
  "next to": "👥",
  "between": "↔️",
  "in front of": "⏩",
  "behind": "🔙",
  "opposite": "🔁",
  "above": "⬆️",

  // Directions
  "turn left": "⬅️",
  "turn right": "➡️",
  "go straight on": "⬆️",

  // Food & drink + and Fruit & vegetables +
  "chips": "🍟",
  "sausages": "🌭",
  "ice cream": "🍨",
  "water": "💧",
  "watermelon": "🍉",
  "grapes": "🍇",
  "pineapple": "🍍",
  "spinach": "🥬",
  "potatoes": "🥔",

  // 1st Grade Additional Topics additions
  "instructions:circle": "⭕",
  "after": "⏩",
  "and": "➕",
  "animal": "🐾",
  "another": "🔁",
  "art": "🎨",
  "below": "⬇️",
  "both": "👥",
  "boy": "👦",
  "card": "🃏",
  "chant": "🎶",
  "children": "🧑‍🤝‍🧑",
  "class": "🧑‍🤝‍🧑",
  "classroom": "🪑",
  "count": "🧮",
  "country": "🗺️",
  "craft": "✂️",
  "cup": "☕",
  "day": "☀️",
  "dear": "💌",
  "design": "📐",
  "else": "🔄",
  "family": "👨‍👩‍👧",
  "favourite": "⭐",
  "follow": "👣",
  "food": "🥪",
  "friend": "🫂",
  "from": "📤",
  "fun": "🎉",
  "game": "🎲",
  "girl": "👧",
  "go back": "🔙",
  "group": "👨‍👩‍👧‍👦",
  "have you got": "❓",
  "hey": "🙋",
  "hi": "👋",
  "i don't know": "🤷",
  "in": "📥",
  "lesson": "📖",
  "love": "❤️",
  "middle": "🎯",
  "moon": "🌙",
  "music": "🎵",
  "need": "🤲",
  "night": "🌃",
  "no": "❌",
  "number": "🔢",
  "order": "📶",
  "our": "🤝",
  "party": "🥳",
  "question": "❔",
  "right": "➡️",
  "ruby": "🔻",
  "scissors": "✂️",
  "shapes": "🔷",
  "story": "📚",
  "sun": "☀️",
  "task": "📝",
  "tell": "🗣️",
  "things": "📦",
  "this is": "👉",
  "through": "🕳️",
  "today": "📆",
  "tomorrow": "⏭️",
  "too": "➕",
  "toys": "🧸",
  "trace": "✏️",
  "true": "✔️",
  "wait": "⏳",
  "week": "🗓️",
  "wheel": "🎡",
  "what's this": "❓",
  "who's this": "🕵️",
  "with": "🧑‍🤝‍🧑",
  "yes": "✅",
  "yesterday": "⏮️",
  "your": "🫵",
  "good": "👍",
  "excellent": "🌟",
  "ok": "👌",
  "horse": "🐴",
  "home": "🏡",
  "land": "🏝️",
  "start": "🏁",
  "finish": "🏁",
  "review": "🔄",
  "christmas": "🎄",
  "father christmas": "🎅",
  "christmas tree": "🎄",
  "stocking": "🧦",
  "bell": "🔔",
  "decorations": "🎀",
  "present": "🎁",
  "circus": "🎪",
  "clown": "🤡",
  "dress up": "🎭",
  "wear": "🧥",
  "clothes": "👗",
  "under": "👇",
  "on": "🔝",
  "over there": "👉",
  "front": "⏩",
  "out": "🚪",
  "before": "⏮️",
  "next": "⏭️",
  "house": "🏠",
  "flat": "🏢",
  "room": "🚪",
  "wall": "🧱",
  "furniture": "🛋️",
  "interior": "🖼️",
  "mirror": "🪞",
  "light": "💡",
  "city": "🏙️",
  "palace": "🏰",
  "markets": "🏪",
  "transport": "🚌",
  "cultures": "🌍",
  "international": "🌐",
  "friendship": "🤝",
  "human": "👤",
  "person": "🧑",
  "letter": "✉️",
  "best": "🥇",
  "wishes": "✨",
  "visit": "🚶‍♂️",
  "call": "📞",
  "send": "📤",
  "cut": "✂️",
  "fold": "📄",
  "decorate": "🎨",
  "prepare": "📋",
  "collage": "🖼️",
  "materials": "📐",
  "creative": "💡",
  "try": "🎯",
  "collaborate": "👥",
  "riddle": "🧩",
  "compare": "⚖️",
  "choose": "👉",
  "correct": "✅",
  "examples": "📝",
  "wake up": "⏰",
  "sleep": "😴",
  "hour": "🕐",
  "life": "🌱",
  "cycle": "🔄",
  "live": "🏠",
  "year": "📅",
  "every": "🔁",
  "giraffe": "🦒",
  "elephant": "🐘",
  "chameleon": "🦎",
  "squirrel": "🐿️",
  "bat": "🦇",
  "footprints": "🐾",
  "jungle": "🌴",
  "forest": "🌲",
  "sea": "🌊",
  "ground": "🌱",
  "grass": "🌿",
  "stick": "🪵",
  "eat": "🍽️",
  "vegetable": "🥦",
  "greedy": "🤑",
  "nice": "😊",
  "cool": "😎",
  "tidy": "🧹",
  "honest": "🤝",
  "bright": "💡",
  "perfect": "💯",
  "important": "⭐",
  "helpful": "🤲",
  "noise": "📢",
  "extra": "➕",
  "first": "🥇",
  "second": "🥈",
  "many": "🔢",
  "all": "👥",
  "false": "❌",
  "very": "🔥",
  "really": "❗",
  "ability": "⚡",
  "come": "🚶",
  "body": "🧍",
  "language": "🗣️",
};
